FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# Install required Python packages
RUN pip install --no-cache-dir \
    minio==7.1.15 \
    boto3==1.28.10 \
    botocore==1.31.10 \ 
    python-dotenv==1.0.0 \
    fastapi==0.95.2 \
    uvicorn==0.21.1