services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - env-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: env_curated
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: postgis
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    networks:
      - env-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgis -d env_curated"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-airflow:1.0
    depends_on:
      postgis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgis:postgis@postgis/env_curated
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
      AIRFLOW_CONN_AWS_DEFAULT: 'aws://minioadmin:minioadmin@?host=http%3A%2F%2Fminio%3A9000'
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-50000}:0"
    networks:
      - env-net
    command: >
      bash -c "
        until airflow db check; do echo 'Waiting for PostGIS'; sleep 5; done
        airflow db init
        airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com
        airflow scheduler &
        airflow webserver
        "

volumes:
  minio_data:
  postgis_data:

networks:
  env-net: